name: Cypress Test Template

# Were we can define the inputs that our action will accept
inputs:
  command:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - uses: supabase/setup-cli@v1
    - uses: actions/setup-node@v3
      with:
        node-version-file: ".nvmrc"
        cache: "yarn"
    - uses: satackey/action-docker-layer-caching@v0.0.11
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
    - name: Start Supabase and .env.test file
      run: |
        supabase start
        sh generate_env.sh
      shell: bash
    - run: yarn install --frozen-lockfile
      shell: bash
    - run: npm run ${{ inputs.command }}
      shell: bash
