name: Cypress Test Template

# Were we can define the inputs that our action will accept
inputs:
  command:
    required: true

runs:
  using: "composite"
  # Defining the action steps(Just one step to be simple)
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: supabase/setup-cli@v1
    - name: Set up Node.js
      id: setup-node
      run: echo "node_version=$(node -pe "require('./package.json').engines.node")" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.setup-node.node_version }}
    - name: Get node_modules cache
      uses: actions/cache@v3
      id: node_modules
      with:
        path: |
          **/node_modules
        # Adding node version as cache key
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.setup-node.node_version }}
    - uses: supabase/setup-cli@v1
    - name: Start Supabase and .env.test file
      run: |
        supabase start
        sh generate_env.sh
      shell: bash
    - run: yarn install --frozen-lockfile
      shell: bash
    - run: npx cypress install
      shell: bash
    - run: npm run ${{ inputs.command }}
      shell: bash
