import "./globals.css";
import Logo from "@/components/Logo";
import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import LogoutButton from "@/components/LogoutButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = createRouteHandlerClient({ cookies });
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en">
      <body>
        <div
          className="flex flex-col items-center min-h-screen"
          style={{ backgroundImage: `url('/images/main-bg.jpg')` }}
        >
          <div className="flex flex-col items-center w-full h-screen">
            <nav className="flex items-center justify-between w-full h-16 px-4 border-b bg-opacity-90 bg-base-200 border-b-foreground/10">
              <div className="flex items-center justify-between w-full max-w-4xl p-3 font-bold text-foreground stat-title">
                <Logo size={30} className="text-lg place-items-center" />
              </div>
              <div className="flex gap-4">
                {user?.user_metadata?.room_id && (
                  <form action={`/api/room/${user?.user_metadata.room_id}/leave`} method="POST">
                    <button className="mr-2 btn btn-sm btn-outline">
                      Leave <span className="hidden sm:block">Room</span>
                    </button>
                  </form>
                )}
                {user && <LogoutButton />}
              </div>
            </nav>

            <div className="flex flex-col items-center justify-center flex-1 w-full px-6 pt-3 overflow-y-auto text-foreground bg-base-200 bg-opacity-95">
              {children}
            </div>
            <footer className="static w-full py-4 border-t bg-opacity-95 bg-base-200 border-t-foreground/5">
              <div className="container mx-auto text-center">
                <p>&copy; 2023 Created By Claudivan Filho.</p>
              </div>
            </footer>
          </div>
        </div>
      </body>
    </html>
  );
}
