name: "database-tests"
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
      - run: supabase db start
      - run: docker ps
      - run: yarn install --frozen-lockfile
      - run: sh generate_env.sh
      - run: npm run e2e:headless
