name: "Supabase Github Hosted Action"
on:
  pull_request:
jobs:
  run-cypress-auth-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/template/cypress"
        with:
          command: e2e:headless:auth
  run-cypress-gamming-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/template/cypress"
        with:
          command: e2e:headless:gamming
  run-cypress-redirects-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "./.github/template/cypress"
        with:
          command: e2e:headless:redirects
