name: "Supabase Github Hosted Action"
on:
  pull_request:
jobs:
  prepare-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start Supabase
        uses: supabase/setup-cli@v1
        run: supabase start
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Tests
        run: |
          sh generate_env.sh
          npm run e2e:headless
