name: "Supabase Github Self Action"
on:
  pull_request:
    tags:
      - "skip-ci" # This tag is used to skip the workflow because the self-hosted action is not running

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: npx supabase db reset
      - run: sh generate_env.sh
      - run: npm run e2e:headless
