name: "database-tests"
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.18.0
      - run: supabase start --debug
      - run: npm run e2e:headless
