name: "database-tests"
on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    env:
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.18.0
      - run: yarn install --frozen-lockfile
      - run: npx supabase db push --db-url=postgresql://postgres:postgres@localhost:54322/postgres
      - run: sh generate_env.sh
      - run: npm run e2e:headless
