name: "database-tests"
on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.18.0
      - run: yarn install
      - run: npx supabase start
      - run: npm run e2e:headless
